imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

easy_admin:
    site_name: 'Administrador'
    design:
        brand_color: '#1ABC9C'
        assets:
            favicon: '/assets/icons/logo_giubergia_ingenieria.png'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Certificado:
            label: 'Certificados'
            class: AppBundle\Entity\Certificado
            form:
                fields:
                    - { property: 'numePrec', label: 'Nº Precinto' }
                    - { property: 'numeReloj', label: 'Nº Reloj' }
                    - { property: 'idAuto', label: 'Dominio', type: 'easyadmin_autocomplete' }
                    - { property: 'idPermi', label: 'Permisionario', type: 'easyadmin_autocomplete' }
                    - { property: 'idReloj', label: 'Reloj', type: 'easyadmin_autocomplete' }
                    - { property: 'idAgen', label: 'Agencia', type: 'easyadmin_autocomplete' }
                    - { property: 'idOblea', label: 'Nº Habilitación', type: 'easyadmin_autocomplete' }
                    - { property: 'idMonto', label: 'Tarifa', type: 'easyadmin_autocomplete' }
                    - { property: 'idTitu', label: 'Titular', type: 'easyadmin_autocomplete' }
            list:
                title: "Lista de Certificados"

            new:
                title: "Nuevo Certificado"
        Agencia:
            label: 'Agencias'
            class: AppBundle\Entity\Agencia
            list:
                title: "Lista de Agencias"
                fields: [ 'nombAgen']
            new:
                title: "Nueva Agencia"
        Auto:
            label: 'Dominios'
            class: AppBundle\Entity\Auto
            list:
                title: "Lista de Dominios"
                fields: [ 'domiAuto', 'anioAuto' ]
            new:
                title: "Nuevo Dominio"
        Oblea:
            label: 'Nº Habilitaciones'
            class: AppBundle\Entity\Oblea
            list:
                title: "Lista de Nº Habilitaciones"
                fields: [ 'numeOblea' ]
            new:
                title: "Nuevo Nº de Habilitacion"
        Chapa:
            label: 'Tipo de Habilitación'
            class: AppBundle\Entity\Chapa
            list:
                title: "Lista de Tipos de Habilitaciones"
                fields: [ 'nombChapa']
            new:
                title: "Nuevo Tipo de Habilitación"
        Marca:
            label: 'Marcas'
            class: AppBundle\Entity\Marca
            list:
                title: "Lista de Marcas"
                fields: [ 'nombMarca']
            new:
                title: "Nueva Marca de Vehículo"
        Modelo:
            label: 'Modelos'
            class: AppBundle\Entity\Modelo
            list:
                title: "Lista de Modelos"
                fields: [ 'nombMode']
            new:
                title: "Nuevo Modelo de Vehículo"
        Monto:
            label: 'Tarifa'
            class: AppBundle\Entity\Monto
            list:
                title: "Lista de Tarifas"
                fields: [ 'bDia', 'bNoch', 'mDia', 'mNoch']
        Permisionario:
            label: 'Permisionarios'
            class: AppBundle\Entity\Permisionario
            list:
                title: "Lista de Permisionarios"
                fields: [ 'nombPermi' ]
            new:
                title: "Nuevo Permisionario"
        Reloj:
            label: 'Relojes'
            class: AppBundle\Entity\Reloj
            list:
                title: "Lista de Relojes"
                fields: [ 'nombReloj' ]
            new:
                title: "Nuevo Reloj"
        Titular:
            label: 'Titular'
            class: AppBundle\Entity\Titular
            list:
                title: "Titular Taller"
                fields: [ 'nombTitu' ]



    list:
        max_results: 10
