imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

easy_admin:
##acciones
    list:
        actions:
            - { name: 'edit', label: 'Modificar'}
            - { name: 'new', label: 'Nuevo'}
            - { name: 'delete', label: 'Eliminar'}
            - { name: 'search', label: 'Buscar'}
    show:
        actions:
            - { name: 'edit', label: 'Modificar'}
            - { name: 'delete', label: 'Eliminar'}
            - { name: 'list', label: 'Volver'}
    new:
        actions:
            - { name: 'list', label: 'Volver al Listado'}
    edit:
        actions:
            - { name: 'delete', label: 'Eliminar'}
            - { name: 'list', label: 'Volver al Listado'}
##diseño layout
    site_name: 'Administrador'
    design:
        form_theme: 'vertical'
        brand_color: '#374089'
        assets:
            favicon: '/assets/icons/logo_giubergia_ingenieria.png'
##formato de fechas y horas
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    entities:
##entidad certificado
        Certificado:
            label: 'Certificados'
            class: AppBundle\Entity\Certificado
            disabled_actions: ['show']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6'}
                    - { property: 'idChapa', label: 'Tipo de Habilitación', type: 'easyadmin_autocomplete' }
                    - { property: 'numeChapa', label: 'Nº Licencia/Oblea' }
                    - { property: 'idAuto', label: 'Dominio', type: 'easyadmin_autocomplete' }
                    - { property: 'idPermi', label: 'Permisionario', type: 'easyadmin_autocomplete' }
                    - { property: 'idAgen', label: 'Agencia', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6'}
                    - { property: 'numePrec', label: 'Nº Precinto' }
                    - { property: 'idReloj', label: 'Reloj', type: 'easyadmin_autocomplete' }
                    - { property: 'numeReloj', label: 'Nº Reloj' }
                    - { property: 'idMonto', label: 'Tarifa', type: 'easyadmin_autocomplete'}
                    - { property: 'idTitu', label: 'Titular', type: 'easyadmin_autocomplete' }
            list:
                title: "Lista de Certificados"
                fields:
                    - { property: 'numeChapa', label: 'Nº Oblea/Licencia'}
                    - { property: 'idAuto', label: 'Dominio'}
                    - { property: 'idPermi', label: 'Permisionario'}
                    - { property: 'numePrec', label: 'Nº Precinto'}
                    - { property: 'idReloj', label: 'Reloj'}
                    - { property: 'numeReloj', label: 'Nº Reloj'}
                    - { property: 'idAgen', label: 'Agencia'}
                    - { property: 'idMonto', label: 'Tarifa'}
            new:
                title: "Nuevo Certificado"
            edit:
                title: 'Editando Certificado'
##entidad Agencia
        Agencia:
            label: 'Agencias'
            class: AppBundle\Entity\Agencia
            form:
                fields:
                    - { property: 'nombAgen', label: 'Nombre Agencia'}
            list:
                title: "Agencias Disponibles"
                fields:
                    - { property: 'nombAgen', label: 'Nombre Agencia'}
            new:
                title: "Crear Nueva Agencia"
            edit:
                title: 'Editando Certificado'
##entidad Auto dominio
        Auto:
            label: 'Dominios'
            class: AppBundle\Entity\Auto
            form:
                fields:
                    - { property: 'domiAuto', label: 'Dominio del Vehículo'}
                    - { property: 'anioAuto', label: 'Año'}
                    - { property: 'idMode', label: 'Modelo', type: 'easyadmin_autocomplete'}
            list:
                title: "Dominios Disponibles"
                fields:
                    - { property: 'domiAuto', label: 'Dominio'}
                    - { property: 'anioAuto', label: 'Año'}
                    - { property: 'idMode', label: 'Modelo'}
            new:
                title: "Crear Nuevo Dominio"
            edit:
                title: 'Editando Dominio'
##entidad Chapa Habilitacion
        Chapa:
            label: 'Tipo de Habilitación'
            class: AppBundle\Entity\Chapa
            form:
                fields:
                    - { property: 'nombChapa', label: 'Tipo Habilitación'}
            list:
                title: "Lista de Habilitaciones"
                fields:
                    - { property: 'nombChapa', label: 'Tipo Habilitación'}
            new:
                title: "Nuevo Tipo de Habilitación"
            edit:
                title: 'Editando Tipo de Habilitación'
##entidad Marca
        Marca:
            label: 'Marcas'
            class: AppBundle\Entity\Marca
            form:
                fields:
                    - { property: 'nombMarca', label: 'Nombre Marca'}
            list:
                title: "Lista de Marcas"
                fields:
                    - { property: 'nombMarca', label: 'Nombre Marca'}
            new:
                title: "Nueva Marca de Vehículo"
            edit:
                title: "Editando Marca de Vehículo"
##entidad Modelo
        Modelo:
            label: 'Modelos'
            class: AppBundle\Entity\Modelo
            form:
                - { property: 'nombMode', label: 'Nombre Modelo'}
                - { property: 'idMarca', label: 'Marca Perteneciente', type: 'easyadmin_autocomplete'}
            list:
                title: "Lista de Modelos"
                fields:
                    - { property: 'nombMode', label: 'Nombre Modelo'}
                    - { property: 'idMarca', label: 'Marca Perteneciente'}
            new:
                title: "Nuevo Modelo de Vehículo"
            edit:
                title: "Editando Modelo de Vehículo"
##entidad Monto
        Monto:
            label: 'Tarifa'
            class: AppBundle\Entity\Monto
            form:
                fields:
                    - { property: 'nombMonto', label: 'Nombre Tarifa'}
                    - { property: 'bDia', label: 'Bajada Bandera de Día'}
                    - { property: 'bNoch', label: 'Bajada Bandera de Noche'}
                    - { property: 'mDia', label: 'Moneda de Día'}
                    - { property: 'mNoch', label: 'Moneda de Noche'}
            list:
                title: "Lista de Tarifas"
                fields:
                    - { property: 'nombMonto', label: 'Nombre Tarifa'}
                    - { property: 'bDia', label: 'Bajada Día'}
                    - { property: 'bNoch', label: 'Bajada Noche'}
                    - { property: 'mDia', label: 'Moneda Día'}
                    - { property: 'mNoch', label: 'Moneda Noche'}
            new:
                title: "Nueva Tarifa"
            edit:
                title: "Editando Tarifa"
##entidad Permisionario
        Permisionario:
            label: 'Permisionarios'
            class: AppBundle\Entity\Permisionario
            form:
                fields:
                    - { property: 'nombPermi', label: 'Nombre y Apellido del Permisionario'}
                    - { property: 'dniPermi', label: 'Nº Documento'}
                    - { property: 'direPermi', label: 'Domicilio'}
            list:
                title: "Lista de Permisionarios"
                fields:
                    - { property: 'nombPermi', label: 'Nombre y Apellido'}
                    - { property: 'dniPermi', label: 'Nº Documento'}
                    - { property: 'direPermi', label: 'Domicilio'}
            new:
                title: "Nuevo Permisionario"
            edit:
                title: "Editando Permisionario"
##entidad Reloj
        Reloj:
            label: 'Relojes'
            class: AppBundle\Entity\Reloj
            form:
                fields:
                    - { property: 'nombReloj', label: 'Nombre de Reloj'}
            list:
                title: "Lista de Relojes"
                fields:
                    - { property: 'nombReloj', label: 'Nombre de Reloj'}
            new:
                title: "Nuevo Reloj"
            edit:
                title: "Editando Reloj"
##entidad Titular
        Titular:
            label: 'Titular'
            class: AppBundle\Entity\Titular
            disabled_actions: ['new', 'delete']
            edit:
                label: 'Editando Titular del Taller'
                fields:
                    - { property: 'nombTitu', label: 'Nombre y Apellido'}
                    - { property: 'domiTitu', label: 'Domicilio'}
                    - { property: 'cuitTitu', label: 'Nº CUIT'}
                    - { property: 'brutTitu', label: 'Nº Ingresos Brutos'}
                    - { property: 'habiTitu', label: 'Habilitacion'}
                    - { property: 'legaTitu', label: 'Nº Metrología legal'}
                    - { property: 'certTitu', label: 'certificado'}
            list:
                title: "Titular Taller"
                fields:
                    - { property: 'nombTitu', label: 'Nombre y Apellido'}
                    - { property: 'domiTitu', label: 'Domicilio'}
                    - { property: 'cuitTitu', label: 'Nº CUIT'}
                    - { property: 'brutTitu', label: 'Nº Ingresos Brutos'}
                    - { property: 'habiTitu', label: 'Habilitacion'}
                    - { property: 'legaTitu', label: 'Nº Metrología legal'}
                    - { property: 'certTitu', label: 'certificado'}
    list:
        max_results: 10
