easy_admin:
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: ''}
            - { name: 'delete', icon: 'trash-o', label: ''}
    new:
        actions:
            - { name: 'list', icon: 'arrow-left', label: 'Volver al listado'}
##diseño layout
    site_name: 'Administrador Ingeniería Giubergia'
    design:
        menu:
            - { entity: 'Certificado', icon: 'id-card' }
            - { entity: 'Auto', icon: 'taxi' }
            - { entity: 'Permisionario', icon: 'users' }
            - { entity: 'Agencia', icon: 'adn' }
            - { entity: 'Monto', icon: 'dollar' }
            - { entity: 'Chapa', icon: 'list-alt' }
            - { entity: 'Reloj', icon: 'clock-o' }
            - { entity: 'Modelo', icon: 'automobile' }
            - { entity: 'Marca', icon: 'tags' }
            - { entity: 'Titular', icon: 'user' }
        form_theme: 'vertical'
        brand_color: '#374089'
        assets:
            favicon: '/assets/icons/logo_giubergia_ingenieria.png'

##formato de fechas y horas
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'

    entities:

##entidad certificado
        Certificado:
            label: 'Certificados'
            class: AppBundle\Entity\Certificado
            controller: AppBundle\Controller\Admin\CertificadoController
            disabled_actions: ['show']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6'}
                    - { property: 'idChapa', label: 'Tipo de Habilitación' }
                    - { property: 'numeChapa', label: 'Nº Licencia/Oblea' }
                    - { property: 'idAuto', label: 'Dominio' }
                    - { property: 'idPermi', label: 'Permisionario' }
                    - { property: 'idAgen', label: 'Agencia'}
                    - { type: 'group', css_class: 'col-sm-6'}
                    - { property: 'numePrec', label: 'Nº Precinto' }
                    - { property: 'idReloj', label: 'Reloj' }
                    - { property: 'numeReloj', label: 'Nº Reloj' }
                    - { property: 'idMonto', label: 'Tarifa'}
                    - { property: 'idTitu', label: 'Titular' }
            list:
                title: "Lista de Certificados"
                actions:
                    - { name: 'imprimir', label: '', icon: 'print'}
                fields:
                    - { property: 'numeChapa', label: 'Nº Oblea/Licencia'}
                    - { property: 'idAuto', label: 'Dominio'}
                    - { property: 'idPermi', label: 'Permisionario'}
                    - { property: 'numePrec', label: 'Nº Precinto'}
                    - { property: 'idReloj', label: 'Reloj'}
                    - { property: 'numeReloj', label: 'Nº Reloj'}
                    - { property: 'idAgen', label: 'Agencia'}
                    - { property: 'idMonto', label: 'Tarifa'}
                sort: 'dateSave'
            new:
                title: "Nuevo Certificado"
                actions:
                    - { name: 'imprimirnew', label: 'Imprimir y Guardar', icon: 'print', class: 'btn-success'}

            edit:
                title: 'Editando Certificado'
            show:
                title: 'Certificado'
##entidad Agencia
        Agencia:
            label: 'Agencias'
            class: AppBundle\Entity\Agencia
            disabled_actions: ['show']
            form:
                fields:
                    - { property: 'nombAgen', label: 'Nombre Agencia'}
            list:
                title: "Lista de Agencias"
                fields:
                    - { property: 'nombAgen', label: 'Nombre Agencia'}
            new:
                title: "Crear Nueva Agencia"
            edit:
                title: 'Editando Certificado'
##entidad Auto dominio
        Auto:
            label: 'Dominios'
            class: AppBundle\Entity\Auto
            controller: AppBundle\Controller\Admin\AutoController
            disabled_actions: ['show']
            form:
                fields:
                    - { property: 'domiAuto', label: 'Dominio del Vehículo'}
                    - { property: 'anioAuto', label: 'Año'}
                    - { property: 'idMode', label: 'Modelo'}
            list:
                title: "Lista de Dominios"
                fields:
                    - { property: 'domiAuto', label: 'Dominio'}
                    - { property: 'anioAuto', label: 'Año'}
                    - { property: 'idMode', label: 'Modelo'}
            new:
                title: "Crear Nuevo Dominio"
            edit:
                title: 'Editando Dominio'
##entidad Chapa Habilitacion
        Chapa:
            label: 'Oblea/Licencia'
            class: AppBundle\Entity\Chapa
            disabled_actions: ['show']
            form:
                fields:
                    - { property: 'nombChapa', label: 'Tipo Habilitación'}
            list:
                title: "Lista de Habilitaciones"
                fields:
                    - { property: 'nombChapa', label: 'Tipo Habilitación'}
            new:
                title: "Nuevo Tipo de Habilitación"
            edit:
                title: 'Editando Tipo de Habilitación'
##entidad Marca
        Marca:
            label: 'Marcas'
            class: AppBundle\Entity\Marca
            disabled_actions: ['show']
            form:
                fields:
                    - { property: 'nombMarca', label: 'Nombre Marca'}
            list:
                title: "Lista de Marcas"
                fields:
                    - { property: 'nombMarca', label: 'Nombre Marca'}
            new:
                title: "Nueva Marca de Vehículo"
            edit:
                title: "Editando Marca de Vehículo"
##entidad Modelo
        Modelo:
            label: 'Modelos'
            class: AppBundle\Entity\Modelo
            controller: AppBundle\Controller\Admin\ModeloController
            disabled_actions: ['show']
            form:
                - { property: 'nombMode', label: 'Nombre Modelo'}
                - { property: 'idMarca', label: 'Marca Perteneciente'}
            list:
                title: "Lista de Modelos"
                fields:
                    - { property: 'nombMode', label: 'Nombre Modelo'}
                    - { property: 'idMarca', label: 'Marca Perteneciente'}
            new:
                title: "Nuevo Modelo de Vehículo"
            edit:
                title: "Editando Modelo de Vehículo"
##entidad Monto
        Monto:
            label: 'Tarifa'
            class: AppBundle\Entity\Monto
            disabled_actions: ['show']
            form:
                fields:
                    - { property: 'nombMonto', label: 'Nombre Tarifa'}
                    - { property: 'bDia', label: 'Bajada Bandera de Día'}
                    - { property: 'bNoch', label: 'Bajada Bandera de Noche'}
                    - { property: 'mDia', label: 'Moneda de Día'}
                    - { property: 'mNoch', label: 'Moneda de Noche'}
            list:
                title: "Lista de Tarifas"
                fields:
                    - { property: 'nombMonto', label: 'Nombre Tarifa'}
                    - { property: 'bDia', label: 'Bajada Día'}
                    - { property: 'bNoch', label: 'Bajada Noche'}
                    - { property: 'mDia', label: 'Moneda Día'}
                    - { property: 'mNoch', label: 'Moneda Noche'}
            new:
                title: "Nueva Tarifa"
            edit:
                title: "Editando Tarifa"
##entidad Permisionario
        Permisionario:
            label: 'Permisionarios'
            class: AppBundle\Entity\Permisionario
            disabled_actions: ['show']
            form:
                fields:
                    - { property: 'nombPermi', label: 'Nombre y Apellido del Permisionario'}
                    - { property: 'dniPermi', label: 'Nº Documento'}
                    - { property: 'direPermi', label: 'Domicilio'}
            list:
                title: "Lista de Permisionarios"
                fields:
                    - { property: 'nombPermi', label: 'Nombre y Apellido'}
                    - { property: 'dniPermi', label: 'Nº Documento'}
                    - { property: 'direPermi', label: 'Domicilio'}
            new:
                title: "Nuevo Permisionario"
            edit:
                title: "Editando Permisionario"
##entidad Reloj
        Reloj:
            label: 'Relojes'
            class: AppBundle\Entity\Reloj
            disabled_actions: ['show']
            form:
                fields:
                    - { property: 'nombReloj', label: 'Nombre de Reloj'}
            list:
                title: "Lista de Relojes"
                fields:
                    - { property: 'nombReloj', label: 'Nombre de Reloj'}
            new:
                title: "Nuevo Reloj"
            edit:
                title: "Editando Reloj"
##entidad Titular
        Titular:
            label: 'Titular'
            class: AppBundle\Entity\Titular
            disabled_actions: ['new', 'delete']
            edit:
                label: 'Editando Titular del Taller'
                fields:
                    - { property: 'nombTitu', label: 'Nombre y Apellido'}
                    - { property: 'domiTitu', label: 'Domicilio'}
                    - { property: 'cuitTitu', label: 'Nº CUIT'}
                    - { property: 'brutTitu', label: 'Nº Ingresos Brutos'}
                    - { property: 'habiTitu', label: 'Habilitacion'}
                    - { property: 'legaTitu', label: 'Nº Metrología legal'}
                    - { property: 'certTitu', label: 'certificado'}
            list:
                title: "Titular Taller"
                fields:
                    - { property: 'nombTitu', label: 'Nombre y Apellido'}
                    - { property: 'domiTitu', label: 'Domicilio'}
                    - { property: 'cuitTitu', label: 'Nº CUIT'}
                    - { property: 'brutTitu', label: 'Nº Ingresos Brutos'}
                    - { property: 'habiTitu', label: 'Habilitacion'}
                    - { property: 'legaTitu', label: 'Nº Metrología legal'}
                    - { property: 'certTitu', label: 'certificado'}
    list:
        max_results: 10
