AppBundle\Entity\Certificado:
    type: entity
    table: certificado
    indexes:
        FK_AUTO_CERT:
            columns:
                - id_auto
        FK_TITU_CERT:
            columns:
                - id_titu
        FK_8B8B21056EC521FB:
            columns:
                - id_permi
        FK_8B8B2105A982CFD9:
            columns:
                - id_reloj
        FK_8B8B2105C1189551:
            columns:
                - id_chapa
        FK_8B8B2105D6E65D60:
            columns:
                - id_agen
        FK_8B8B2105FE57C495:
            columns:
                - id_monto
    uniqueConstraints:
        nume_chapa:
            columns:
                - nume_chapa
    id:
        idCert:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_cert
            generator:
                strategy: IDENTITY
    fields:
        numeChapa:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nume_chapa
        numePrec:
            type: bigint
            nullable: true
            options:
                unsigned: false
                comment: 'numero de precinto'
                default: '0'
            column: nume_prec
        numeReloj:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: s/n
            column: nume_reloj
        dateSave:
            type: datetime
            nullable: true
            column: date_save
    manyToOne:
        idTitu:
            targetEntity: Titular
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_titu:
                    referencedColumnName: id_titu
            orphanRemoval: false
        idPermi:
            targetEntity: Permisionario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_permi:
                    referencedColumnName: id_permi
            orphanRemoval: false
        idReloj:
            targetEntity: Reloj
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_reloj:
                    referencedColumnName: id_reloj
            orphanRemoval: false
        idChapa:
            targetEntity: Chapa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_chapa:
                    referencedColumnName: id_chapa
            orphanRemoval: false
        idAgen:
            targetEntity: Agencia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_agen:
                    referencedColumnName: id_agen
            orphanRemoval: false
        idAuto:
            targetEntity: Auto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_auto:
                    referencedColumnName: id_auto
            orphanRemoval: false
        idMonto:
            targetEntity: Monto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_monto:
                    referencedColumnName: id_monto
            orphanRemoval: false
    lifecycleCallbacks: {  }
