AppBundle\Entity\Chapa:
    type: entity
    table: chapa
    uniqueConstraints:
        nomb_chapa:
            columns:
                - nomb_chapa
    id:
        idChapa:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_chapa
            generator:
                strategy: IDENTITY
    fields:
        nombChapa:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: nomb_chapa
    lifecycleCallbacks: {  }
