AppBundle\Entity\Reloj:
    type: entity
    table: reloj
    uniqueConstraints:
        nomb_reloj:
            columns:
                - nomb_reloj
    id:
        idReloj:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_reloj
            generator:
                strategy: IDENTITY
    fields:
        nombReloj:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: nomb_reloj
    lifecycleCallbacks: {  }
