AppBundle\Entity\Titular:
    type: entity
    table: titular
    id:
        idTitu:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_titu
            generator:
                strategy: IDENTITY
    fields:
        nombTitu:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: nomb_titu
        domiTitu:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: domi_titu
        cuitTitu:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: cuit_titu
        brutTitu:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: brut_titu
        habiTitu:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: habi_titu
        legaTitu:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: lega_titu
        certTitu:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: cert_titu
    lifecycleCallbacks: {  }
